{% set name = "disjoint-set" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name | replace("-", "_") }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: cc09320b35d5a5bb36ceba86ab885b073340d0ba05cd92e9bd413fbea026162a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=1.1.0
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - disjoint_set

about:
  home: https://pypi.org/project/disjoint-set/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: DisjointSet (a.k.a. union–find data structure or merge–find set) implementation for Python.
  dev_url: https://github.com/mrapacz/disjoint-set

extra:
  recipe-maintainers:
    - rpetit3
